list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/")
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/packages")

set(THIRD_PARTY "third-party" CACHE STRING "3rdparty folder for project dependencies. [Don't change this variable.]")

find_package(Git)
if(Git_FOUND)
  message("Git found: ${GIT_EXECUTABLE}")
endif()

find_package(Boost      REQUIRED)
find_package(OpenSSL    REQUIRED)
find_package(Cryptopp   REQUIRED)
find_package(OpenCV     REQUIRED)
find_package(OpenMesh   REQUIRED)
find_package(GTest      REQUIRED)
find_package(DocTest    REQUIRED)
find_package(Catch2     REQUIRED)
find_package(Curl       REQUIRED)
find_package(Fmt        REQUIRED)
find_package(Jwt        REQUIRED)
find_package(JSon       REQUIRED)
find_package(Ctre       REQUIRED)
find_package(Zlib       REQUIRED)
find_package(Eigen      REQUIRED)

if (USE_CUSTOM_ENGINE)
  find_package(${ENGINE_CODE_NAME}  REQUIRED)
endif()
